print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/hugonygren/Documents/GitHub/HilbertsHotel/Hilberts Hotel/Assets/Hugo/corridor_FINAL2.mb"`)
{		
	file -o "/Users/hugonygren/Documents/GitHub/HilbertsHotel/Hilberts Hotel/Assets/Hugo/corridor_FINAL2.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/hugonygren/Documents/GitHub/HilbertsHotel/Hilberts Hotel/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/hugonygren/Documents/GitHub/HilbertsHotel/Hilberts Hotel/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/hugonygren/Documents/GitHub/HilbertsHotel/Hilberts Hotel/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
